### ISSUE TITLE
_http_common

### ISSUE THREAD

**Issue by richnolyn** [helperdiscord/petitio#35]
## Bug Description

Module not found: Error: Can't resolve '_http_common'

## Reproducible By

Erela.js manager // anything 

## Expected Behavior

obvious?

## Logs & Screenshots

`ERROR in ./node_modules/petitio/dist/index.js 1:997-1020
Module not found: Error: Can't resolve '_http_common' in 'C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\petitio\dist'
resolve '_http_common' in 'C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\petitio\dist'
  Parsed request is a module
  using description file: C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\petitio\package.json (relative path: ./dist)
    resolve as module
      C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\petitio\dist\node_modules doesn't exist or is not a directory
      C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\petitio\node_modules doesn't exist or is not a directory
      C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules
        single file module
          using description file: C:\Users\Nolly\Desktop\Undetected\nolynjs\package.json (relative path: ./node_modules/_http_common)
            no extension
              C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common doesn't exist
            .tsx
              C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common.tsx doesn't exist
            .ts
              C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common.ts doesn't exist
            .js
              C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common.js doesn't exist
            .jsx
              C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common.jsx doesn't exist
        C:\Users\Nolly\Desktop\Undetected\nolynjs\node_modules\_http_common doesn't exist
      C:\Users\Nolly\Desktop\Undetected\node_modules doesn't exist or is not a directory
      C:\Users\Nolly\Desktop\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Nolly\node_modules
        single file module
          No description file found in C:\Users\Nolly\node_modules or above
          no extension
            C:\Users\Nolly\node_modules\_http_common doesn't exist
          .tsx
            C:\Users\Nolly\node_modules\_http_common.tsx doesn't exist
          .ts
            C:\Users\Nolly\node_modules\_http_common.ts doesn't exist
          .js
            C:\Users\Nolly\node_modules\_http_common.js doesn't exist
          .jsx
            C:\Users\Nolly\node_modules\_http_common.jsx doesn't exist
        C:\Users\Nolly\node_modules\_http_common doesn't exist
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory`

## Environment

Windows LTS, NodeJS LTS

**Comment by tbnritzdoge** [comment]
@richnolyn which version of petitio is this?
